/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScreeningStageIdRouteImport } from './routes/screening.$stageId'

const ScreeningStageIdRoute = ScreeningStageIdRouteImport.update({
  id: '/screening/$stageId',
  path: '/screening/$stageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/screening/$stageId': typeof ScreeningStageIdRoute
}
export interface FileRoutesByTo {
  '/screening/$stageId': typeof ScreeningStageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/screening/$stageId': typeof ScreeningStageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/screening/$stageId'
  fileRoutesByTo: FileRoutesByTo
  to: '/screening/$stageId'
  id: '__root__' | '/screening/$stageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ScreeningStageIdRoute: typeof ScreeningStageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/screening/$stageId': {
      id: '/screening/$stageId'
      path: '/screening/$stageId'
      fullPath: '/screening/$stageId'
      preLoaderRoute: typeof ScreeningStageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ScreeningStageIdRoute: ScreeningStageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
